### ISSUE TITLE
Home Page- Ajout bouton

### ISSUE THREAD

**Issue by simple-acces** [district30/website#1]
Rajouter un bouton 'Contactez-nous' en bas de la section 'devenir franchisé'. 
Reprendre le bouton 'envoyez votre message' de la section formulaire de contact, passer le fond en jaune (cf couleur menu au roll) (police blanc).
Centrer le bouton sur le titre 'devenir franchisé'

**Comment by gh-romain-guilmet** [comment]
Alors sur un fond jaune je proposerais plus du noir en couleur de police (le blanc ne sera pas très lisible)

**Comment by simple-acces** [comment]
ca me va!
