### ISSUE TITLE
CTA sur toutes les pages

### ISSUE THREAD

**Issue by simple-acces** [district30/website#22]
Sur chaque page la fleche de l'accueil est bleu au roll tu peux la mettre jaune stp?

**Comment by gh-romain-guilmet** [comment]
En gros tu veux que la couleur ne change pas au roll c'est ça ? (Ou j'ai pas compris la demande ?)

**Comment by simple-acces** [comment]
C'est excatement ça. Ce bleu est un reliquat d'un autre site ;)
