### ISSUE TITLE
reCAPTCHA

### ISSUE THREAD

**Issue by simple-acces** [district30/website#28]
Je n'ai plus de captcha sur les pages district30, uniquement sur la HP

**Comment by simple-acces** [comment]
Coucou! ;)

**Comment by RonanDrouglazet** [comment]
N'hésite pas à me ping à la maison quand c'est urgent comme ça ;) 
je vais essayer de regarder ça ce midi, tu bosses sur le site là ?

**Comment by simple-acces** [comment]
euh comment je ping... ? non je travaillepas dessus la mais c'est pas non plus mega urgent

**Comment by RonanDrouglazet** [comment]
quand je dis "ping" c'est pour dire n'hésite pas à m'en parler :p 
ping=apporter un sujet à mon attention 😬
