### ISSUE TITLE
Page Ninja/ Danse/ Fitness/ Cross - Section tarif & planing

### ISSUE THREAD

**Issue by simple-acces** [district30/website#4]
Passer l'image et le texte sur 2 colonnes (au lieu de l'un à la suite de l'autre).
Dans la colonne du texte ('colonne tarif') insérer 3 boutons (design du bouton du formulaire de contact, jaune et police blanc)

**Comment by gh-romain-guilmet** [comment]
J'ai mis en ligne une première version dis moi ce que tu en penses
