### ISSUE TITLE
Page Ninja/Danse/Fitness/Cross - Section Galerie

### ISSUE THREAD

**Issue by simple-acces** [district30/website#6]
Faire le point avec Ronan sur la construction et compatibilité avec Octoboot
Dans le section 'le district en images', créer une galerie voici le modèle de base:
https://www.templatemonster.com/fr/demo/61382.html
Adaptation à District 30:
- Je voudrais que les photos miniatures soit en 200x200px
- Au roll sur une miniature:  effet grisé (cf photos des coachs) + loupe + (http://getbootstrap.com/components/    glyphicon glyphicon-zoom-in)
- Au clic: idem que sur le modele

**Comment by gh-romain-guilmet** [comment]
Note à moi-même : 
- mettre la grande image dans la div de la petite en display: none
- générer la galerie au clic sur une image et afficher l'image qui vient d'être sélectionnée
- dans le before save du script.js fermer la galerie pour rétablir l'état initial
