### ISSUE TITLE
HP police - La salle

### ISSUE THREAD

**Issue by simple-acces** [district30/website#9]
Changer la police de la partie la salle --> reprendre celle des districts

**Comment by simple-acces** [comment]
Me suis fait voler mon ticket!!

**Comment by gh-romain-guilmet** [comment]
Oups désolé, je ferais gaffe pour la prochaine fois j'ai pas pensé que c'était pas que des tâches qui m'étaient attribuées

**Comment by simple-acces** [comment]
;)
